### ISSUE TITLE
Fresh Install Issues, features

### ISSUE THREAD

**Issue by brianhoffman1980** [MOnSieurFPGA/MOnSieurFPGA-SD_Image_Builds#1]
I performed a clean install of the image on a new SD card, after saying Y to the install options I can boot successfully. Here is where I am stuck.
1.  Mister Menu doesn't have Cores. All I see on the main screen are OTHER and UTILITY, it seems the cores are not installed.
2.  As I am a windows user (I know, I know) I placed the SD card in my computer but I do not see on the FAT filesystem a structure to copy Scripts to, I was going to use UPDATE ALL, and tell it NOT to update Linux. So Im a little stuck here.
3. I tired navigating to \\IPADDRESS\ of the Mister , but it doesnt seem any partitions\folders are shared that I can use to move files to where they need to go.
4. When I tried to enable SAMBA from the utilities, I get a Locale error, probably not a stopper, but something is missing or refrenced that isnt set by default or where its looking for it.
5. I tried to FTP to the Mister to see if I could copy files to it and it isnt enabled with no clear easy way to enable it.

Aside from the above, it seems to boot and everything, just cant use it and really check it out yet.
Thank you all for the hard work. and I apologize for adding so many things in one thread.

**Comment by atrac17** [comment]
See the packages repository. I'm pretty sure I point to the readme, if I
don't my bad. Cores are split so you put what you want to install.

**Comment by djhardrich** [comment]
Tt

Going to try to help here one by one, and no need to apologize, we’re working on more documentation but this will hopefully help others get going as well:

1. `sudo pacman -Sy JTFPGA-MiSTer MiSTer-Devel-Arcade MiSTer-Devel-Computer MiSTer-Devel-Console PSX-MiSTer-Devel-Unstable —overwrite “*”` (two dashes before overwrite, type in “alarm” or your user password if you’ve changed it with passwd when asked) will get you all of the cores, `sudo pacman -Syuu` will perform a system update (including cores when new packages are pushed, atrac17 is almost done with automated package builds) 

2. While update_all will work, it can break package updates, I’d like to figure something out with thepsylon soon (awesome person who does awesome work!) where the “getter scripts” etc are pulled in from an Arch repo he controls or something like that… If you use an SFTP client to copy update_all.sh to /home/alarm (default sftp directory) then ssh into your de10, run “chmod +x update_all.sh” and “./update_all.sh” it -should- run, if something fails because of missing packages, use “sudo pacman -Sy archpackagenamegooglehelps” to install them. Using `chmod +x` to make “getter” scripts executable and running them will work too.

3. CIFS packages are installed by default, but not pre-configured, stock MiSTer scripts for bluetooth/smb probably won’t work out of the box (I know the bluetooth ones don’t, new ones are being worked on)

4. “sudo pacman -Sy locale” should fix that for you :)

5. Use an SFTP client (cyberduck and filezilla both work well on Windows) and use port 22 to denote sftp. Log in as user “alarm” and either change directories to /media/fat/games and copy files, or copy them to a new folder in your home directory with subdirectories for systems, then ssh in and run `mv newfolder/* /media/fat/games/` . If you get permission errors trying to do any of the above things, running `sudo chown -R alarm /media/fat/games` will fix it. PROTIP: running “sudo systemctl stop MiSTer” before transferring files via sftp and running “sudo systemctl start MiSTer” when you’re done can speed up file transfers :)

Hope this helps get you going!

**Comment by brianhoffman1980** [comment]
I think I am misunderstanding where to add the password, I didnt change it yet.

[alarm@alarm ~]$ sudo pacman -Sy JTFPGA-MiSTer MiSTer-Devel-Arcade MiSTer-Devel-Computer MiSTer-Devel-Console PSX-MiSTer-Devel-Unstable —overwrite “*”
error: could not register 'monsieur' database (database already registered)
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 alarm is up to date
 aur is up to date
 monsieur is up to date
error: target not found: —overwrite
error: target not found: “*”
[alarm@alarm ~]$

Ill hold off on the update_all script, my first goal is to make sure games launch.
Second goal is to test launching games over ssh with MGL files which I got working in stock Mister build with this time command.
echo load_core "/media/fat/Mgl/StarFox.mgl" > /dev/MiSTer_cmd
echo load_core "/media/fat/Mgl/FFVII.mgl" > /dev/MiSTer_cmd

If all that goes well, the biggest challenge will be to try and figure out how to compile and install EmulationStation frontend, then see about using the above command with it to lauch games from its menu system.

Then the best way to kill games and get back into ES

Then a script to autogenerate MGL based on what roms exist.

Should be really fun.

**Comment by djhardrich** [comment]
Sorry, github mangled the command when I posted from my phone, I've updated from my laptop (note the double-dashes before overwrite, that's super important, also the asterisk inside of the quotes after the overwrite flag :)

**Comment by brianhoffman1980** [comment]
This seems to be working! Downloading now, and I believe I can resolve this. Im sure Ill be back!
